var object = "Retrato";
var face = "Mulher";
var landscape = "Pinhal";
var length = 10;
var width = 5;
var perimeter = length + length + width + width;
console.log("Object:" + object);
console.log("Face:" + face);
console.log("Landscape:" + landscape);
console.log("Perimeter:" + perimeter);
